version: '3'
services:
  app_redis:
    container_name: orlandocc_2018_graphql_redis
    image: redis:3.2
    ports:
      - 62001:6379
  app:
    container_name: orlandocc_2018_graphql
    build: .
    volumes:
      - ./index.js:/app/index.js
      - ./package.json:/app/package.json
      - ./api:/app/api
      - ./public:/app/public
      - ./src:/app/src
      - ./build:/app/build
      - ./yarn.lock:/app/yarn.lock
      - ./start.sh:/app/.start.sh
      - ./ssl:/app/ssl
    depends_on:
      - app_redis
    links:
      - app_redis
    ports:
      - 62004:3000 # React Development Server
      - 62002:3001 # Web API
      - 62005:443 # Local HTTPS
      - 62003:5858 # Debugging port for Web API
    environment:
      REDIS_URL: redis://app_redis:6379
      JWT_SECRET: shhh-orlando-code-camp-2018
      JWT_EXPIRES_IN: "1d"
      REACT_APP_GRAPHQL_HTTP_URI: "http://localhost:62002/api"
      REACT_APP_GRAPHQL_WS_URI: "ws://localhost:62002/"
      WS_PORT: 62002 # WebSockets - in prod it's the same as PORT, but since we proxy through Docker locally, we separate
    command: ["node", "docker.js"]
    restart: always
